// Built-in cassette data recorder. The machine side is the 8255 wiring;
// media is represented as a mono PCM waveform so ROM and application tape
// routines see the same one-bit signal they would receive from the deck.
#pragma once

#include <cstddef>
#include <cstdint>
#include <vector>

namespace mz {

class CmtDeck {
public:
    enum class Transport : uint8_t { Stop = 0, Play = 1, FastForward = 2, Rewind = 3 };

    void reset(uint64_t now = 0);
    void set_mz80b_mode(bool enabled) { mz80b_mode_ = enabled; }
    bool load_wav(const uint8_t* data, size_t size);
    // Load a standard MZF logical tape image (also used by MZT/M12) and turn
    // its header/data records into comparator pulses.
    bool load_mzf(const uint8_t* data, size_t size, bool mz80b_mode = false);
    bool create_blank(uint32_t seconds, uint32_t sample_rate = 44100);
    void eject();

    // 8255 output pins. `enabled` follows the programmed port direction;
    // the first driven value establishes a baseline and cannot accidentally
    // turn four transport solenoids on after an 8255 mode-set latch clear.
    void set_port_a(bool enabled, uint8_t value, uint64_t now);
    void set_port_c(bool enabled, uint8_t value, uint64_t now);

    // Cabinet buttons for the browser UI. KINH (port C bit5) inhibits these,
    // but never inhibits commands generated by the CPU through port A.
    void manual_command(Transport command, uint64_t now);

    void sync(uint64_t now);
    bool read_data(uint64_t now);
    bool running(uint64_t now);
    uint64_t position_samples(uint64_t now);

    bool tape_loaded() const { return inserted_; }
    bool write_protected() const { return write_protected_; }
    void set_write_protected(bool on) { write_protected_ = on; }
    Transport transport() const { return transport_; }
    bool recording() const {
        return inserted_ && transport_ == Transport::Play && port_c_enabled_ &&
               !(port_c_ & 0x40) && !write_protected_;
    }
    uint32_t sample_rate() const { return sample_rate_; }
    uint64_t duration_samples() const { return samples_.size(); }
    uint64_t duration_ms() const;
    uint64_t position_ms(uint64_t now);

    bool dirty() const { return dirty_; }
    void clear_dirty() { dirty_ = false; }
    std::vector<uint8_t> wav_image() const;

    // Deterministic fixtures avoid putting encoded WAV byte arrays in tests.
    void mount_pcm_for_test(std::vector<int16_t> samples, uint32_t sample_rate);
    int16_t sample_for_test(size_t index) const { return samples_.at(index); }

private:
    static constexpr int FAST_SPEED = 8;
    static constexpr int16_t RECORD_LEVEL = 24576;

    void command(Transport command);
    void finish_play_end();
    void finish_rewind_start();
    void set_media(std::vector<int16_t> samples, uint32_t sample_rate);

    std::vector<int16_t> samples_;
    bool inserted_ = false;
    uint32_t sample_rate_ = 44100;
    uint64_t position_ = 0;
    uint64_t last_cycle_ = 0;
    uint64_t sample_fraction_ = 0;
    Transport transport_ = Transport::Stop;
    bool write_protected_ = false;
    bool dirty_ = false;

    bool port_a_enabled_ = false;
    bool port_c_enabled_ = false;
    uint8_t port_a_ = 0xFF;
    uint8_t port_c_ = 0xFF;
    uint8_t port_a_armed_ = 0;
    bool open_armed_ = false;
    bool mz80b_mode_ = false;
};

} // namespace mz
